### PR TITLE
Created workout table with exercises

### PR DESCRIPTION
**Pull request by adamgrif**
#76 
Table is a bit ugly but fine for right now - tried to clean up alignment for awhile and it just wasn't workin for me, I'll update in next sprint.

### CODE REVIEW

**Comment by jackbrewer7** [comment]
I tested out the code, and when you add a new workout, it looks like the workout names all go blank after the page refreshes. Can you try to recreate this?

**Review by mfarber99 — COMMENTED** [review]
Any build files or nah?

**Comment by adamgrif** [comment]
> Can you try to recreate this?

Weird I'm not getting that issue. I've tried a bunch of different ways to try and force it but it all works for me. Any idea what error is causing the blank table?

> Any build files or nah?

There were like 20 modifications/deletions but they aren't necessary to commit afaik - I tested with a clean repo and just the new Workouts.js and it built correctly.

**Comment by jackbrewer7** [comment]
I just tried on Mark's computer, we can go over in discussion later, but we get it when:

1) Load the app
2) Sign In
3) Add Workout
4) Enter workout name, days of week, and exercises
5) Click Add
6) All of the workout names go blank

The problem could be how we add them, or maybe even with the calendar. I can investigate later too.

**Comment by adamgrif** [comment]
Strange, I follow the same path and it works. Yeah let's chat in discussion.

**Pull request merged**
