### PR TITLE
adding add exercise button and form

### LINKED ISSUE #39: Create add button and popup modal form on frontend

### PR DESCRIPTION
**Pull request by maddywestergaard**
#39

### CODE REVIEW

**Review by jackbrewer7 — COMMENTED** [review]
The front end looks great! I think we should change the button to add exercise, not add workout.

**Comment by maddywestergaard** [comment]
> The front end looks great! I think we should change the button to add exercise, not add workout.

oops my bad, fixed

**Review by mfarber99 — CHANGES_REQUESTED** [review]
Agreed with Jack, the button should be called “Add Exercise” and maybe moved above the “Workouts” header 😬 Also, if you have any build files to commit, please do so since we’ve had some issues in the past with future builds after not committing them. Otherwise, looks awesome! 

Edit: Just curious, does sending data to the backend work after submitting the form and hardcoding the email? I’m curious how/if the JS number to Java int conversion works

**Comment by maddywestergaard** [comment]
> Agreed with Jack, the button should be called “Add Exercise” and maybe moved above the “Workouts” header 😬 Also, if you have any build files to commit, please do so since we’ve had some issues in the past with future builds after not committing them. Otherwise, looks awesome!
> 
> Edit: Just curious, does sending data to the backend work after submitting the form and hardcoding the email? I’m curious how/if the JS number to Java int conversion works

added build files & moved button above header
and im not entirely sure about the backend stuff, I was able to send the json object to the create exercise service & it was parsed correctly but beyond that im not sure how it works; it hasn't successfully updated the db so somethings not working right

**Comment by jackbrewer7** [comment]
I can look into the connection to the backend this weekend.

**Comment by mfarber99** [comment]
> I can look into the connection to the backend this weekend.

I know the issue

**Pull request merged**
